FROM python:3.8

ADD requirements.txt ./

RUN pip install --upgrade pip && pip install beautifulsoup4 pandas boto3 requests s3fs

ENV LOG=1

ADD accessKeys.csv /preprocessing/accessKeys.csv

ADD last30days.py /preprocessing/last30days.py

EXPOSE 8000

VOLUME //preprocessing/

WORKDIR /preprocessing/

CMD python3 last30days_retired.py
