version: '3.8'
services:
  streamlit:
    build:
      context: ..
      dockerfile: Docker/app/Dockerfile_streamlit
    ports:
      - "8501:8501"
    networks:
      - app-network

  fastapi:
    build:
      context: ..
      dockerfile: Docker/api/Dockerfile_fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network

  training:
    build:
      context: ..
      dockerfile: Docker/training/Dockerfile_training
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
