# Image de base pour Streamlit
FROM python:3.8

# Installation de Streamlit
RUN pip install streamlit

# Copie des fichiers de l'application Streamlit dans le conteneur
COPY ./streamlit_app /app
WORKDIR /app

# Exposition du port pour Streamlit
EXPOSE 8501

# Commande pour exécuter Streamlit
CMD ["streamlit", "run", "app.py"]
