name: ci

on:
  push:
    branches:
      - master

jobs:
  testing01:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Node CI 
      uses: octodemo/devoxx-2021-node@master
      with:
        node-version: ${{ matrix.node }}
