name: Run API container

on: push

jobs:
  docker:
    
    name: Run image built
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull and Run Docker Image
        run: |
          docker pull dropolic/alpine-api-image:latest
          docker run -d --name container-api-alpine -p 8001:8001 dropolic/alpine-api-image:latest

      - name: Check running containers
        run: docker ps

      - name: Verify API 
        run: curl http://localhost:8001
