name: Running API container
on: push

jobs:
  compile:
    name: Running API container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run Docker container for API
        run: |
          docker pull dropolic/alpine-api-image:latest
          docker run -d --name api_container -v ${{ github.workspace }}:/src dropolic/alpine-api-image:latest
          docker exec api_container python3 /src/api_sentiment_analysis_OAuth.py

      - name: Verify assets
        run: ls -l dist
