name: Build and run API container

on: push

jobs:

  test:
    runs-on: ubuntu-latest
    setps:
      - uses: actions/checkout@v3
        name: Test python code
        run: | 
          pip3 install -r requirements.txt
          cd src/test_api/
          pytest

  
  build-push-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build -t dropolic/alpine-api-image:${GITHUB_SHA} .
          docker tag  dropolic/fast-api:${GITHUB_SHA} dropolic/alpine-api-image:latest
          docker images
          docker run -d -p 8001:8001 --name fastapi dropolic/alpine-api-image:${GITHUB_SHA}
          sleep 10
          docker login -u ${{ secrets.REGISTRY_USER  }} -p ${{ secrets.REGISTRY_PASSWD  }}
          docker push dropolic/alpine-api-image:${GITHUB_SHA}
          docker push dropolic/alpine-api-image:latest
    
    run-container:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          run: /
            docker run -d --name container-api-alpine -p 8001:8001 dropolic/alpine-api-image:latest
