name: Running API container
on:
  workflow_dispatch:

jobs:
  docker:
    name: Run image built
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3
        
      - name: Build docker image

      - name: Run Image
        uses: c-schicho/DockerRun-Action@v1
        with:
          image: dropolic/alpine-api-image
          run: echo "hello world"

