name: Build and run API container

on: push

jobs:
  checkout-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

  build-push-container:
    needs: checkout-repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker build ./src/api -t build-api-image:test
          docker tag build-api-image:test dropolic/build-api-image:latest
          docker tag build-api-image:test dropolic/build-api-image:test
          docker images
          docker run -d --name container-api-build -p 8008:8001 build-api-image:test
          sleep 10
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWD }}
          docker push dropolic/build-api-image:test
          docker push dropolic/build-api-image:latest
  
  deploy:
    needs: build-push-container
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME  }}
        username: ${{ secrets.USER_NAME  }}
        key: ${{ secrets.PRIVATE_KEY  }}
        port: 22
        script: |
          sudo docker rm -f project-api 
          sudo docker rmi dropolic/build-api-image:latest
          sleep 10 
          sudo docker run -d -p 8001:8001 --name project-api dropolic/build-api-image:latest
          sudo docker ps 
          sleep 10 
          curl localhost:8001
          ls 
          sudo docker images
